Update game
SR123456789-maker/intoductio-to-github pull request #1
Opened 2023-07-22 13:13 UTC by SR123456789-maker

hi

2023-07-22 13:16 UTC, SR123456789-maker commented on README.md
> -- **How long**: This course takes less than 30 minutes to complete.
hi

2023-07-22 13:28 UTC, SR123456789-maker reviewed
hi

2023-07-22 13:31 UTC, SR123456789-maker commented
nice

2023-07-23 08:23 UTC, SR123456789-maker commented on README.md
sibfhf

2023-07-23 08:23 UTC, SR123456789-maker commented on README.md
ni

2023-07-23 08:35 UTC, saada1246-makers approved these changes
very nice

2023-07-23 08:35 UTC, saada1246-makers commented on README.md
> +  Define terms and link to docs.github.com.
ver nicce definitely

2023-07-23 08:44 UTC, saada1246-makers requested changes
very nice

2023-07-23 08:45 UTC, saada1246-makers commented
@gsuf

2023-07-23 08:46 UTC, merged

2023-07-23 09:04 UTC, saada1246-makers reviewed
very

2023-07-23 09:04 UTC, saada1246-makers commented on README.md
> -- **Prerequisites**: We assume you are familiar with creating branches, commits, and pull requests—you can learn this in our [Introduction to GitHub](https://github.com/skills/introduction-to-github)
nice